### ISSUE TITLE
README code snippets not accurate to current SDK

### ISSUE THREAD

**Issue by ghost** [anthropics/anthropic-sdk-java#34]
The README section for creating a resource seems to be inaccurate to the currently available methods.

The `maxToken` should be `maxTokens` and the `message` should be `messages`, at least from what I can observe from using the latest version of the anthropic java sdk.

This updated version would be the following:

```java
MessageCreateParams params = MessageCreateParams.builder()
    .maxTokens(1024L)
    .messages(List.of(MessageParam.builder()
        .role(MessageParam.Role.USER)
        .content(MessageParam.Content.ofString("Hello, Claude"))
        .build()))
    .model(Model.CLAUDE_3_5_HAIKU_LATEST)
    .build();
Message message = client.messages().create(params);
```

**Comment by TomerAberbach** [comment]
This will be fixed once https://github.com/anthropics/anthropic-sdk-java/pull/23 is merged
